# Generated by Django 6.0.1 on 2026-01-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='data_criacao',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='titulo',
            new_name='title',
        ),
    ]
