# Generated by Django 6.0.1 on 2026-01-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_ativo_course_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='active',
            new_name='published',
        ),
    ]
