# Generated by Django 6.0.1 on 2026-01-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_create_date_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='workload',
            field=models.IntegerField(default=0),
        ),
    ]
